name: Android Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Unity Library
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-Android-${{ hashFiles('Packages/manifest.json','ProjectSettings/ProjectVersion.txt') }}
          restore-keys: |
            Library-Android-

      - name: Build Android APK
        uses: game-ci/unity-builder@v5
        with:
          unityVersion: 6000.6.3f1
          targetPlatform: Android
          buildMethod: BuildScript.BuildAndroid
          androidExportType: androidPackage
          unityEmail: ${{ secrets.UNITY_EMAIL }}
          unityPassword: ${{ secrets.UNITY_PASSWORD }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: cyber-run-apk
          path: build/**/*.apk
